rgname                 = "stage-vru-rg"
service_principal_name = "stage-vru-spn"
keyvault_name          = "stage-vru-kv-101"
SUB_ID = ""
node_pool_name = "stagenp"
cluster_name = "stage-vru-cluster"
